source "https://rubygems.org"
gem "base64"
gem "cgi"
gem "csv"
gem "digest"
gem "fileutils"
gem "front_matter_parser"
gem "icalendar"
gem "jekyll"
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
end
gem "minima"
gem "nokogiri"
gem "open-uri"
gem "reverse_markdown"
gem "rss"
gem "time"
gem "uri"
gem "yaml"
