#!/usr/bin/env bash

set -e # exit if any command fails

if ! command -v rbenv &>/dev/null; then
  ./script/ensure-git

  OS="$(uname -s)"
  case "$OS" in
  Darwin)
    ./script/ensure-homebrew
    brew install rbenv
    ;;
  Linux)
    . /etc/os-release
    if [ "$ID" == "ubuntu" ]; then
      sudo apt-get install -y -q pkg-config rbenv ruby-dev
      git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      cd ~/.rbenv && src/configure && make -C src
      # shellcheck disable=SC2016
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >>~/.bashrc
      # shellcheck disable=SC2016
      echo 'eval "$(rbenv init -)"' >>~/.bashrc
      mkdir -p "$(rbenv root)"/plugins
      git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
    else
      echo "Unsupported Linux distribution." >&2
      exit 1
    fi
    ;;
  *)
    echo "Unsupported operating system: $OS" >&2
    exit 1
    ;;
  esac
fi
