#!/usr/bin/env bash

set -e # exit if any command fails

if [ ! -f ".ruby-version" ]; then
  echo "Error: .ruby-version file does not exist." >&2
  exit 1
fi
if [ ! -f ".ruby-gemset" ]; then
  echo "Error: .ruby-gemset file does not exist." >&2
  exit 1
fi

DESIRED_RUBY_VERSION="$(cat .ruby-version)"

if command -v ruby >/dev/null; then
  installed_ruby_version=$(ruby -v | awk '{print $2}')
  if [ "$installed_ruby_version" == "$DESIRED_RUBY_VERSION" ]; then
    exit 0
  fi
fi

OS="$(uname)"
if [ "$OS" == "Linux" ]; then
  . /etc/os-release
  if [ "$ID" == "ubuntu" ]; then
    sudo apt-get install -y -q gcc make zlib1g-dev libffi-dev build-essential
  else
    echo "This script supports only ubuntu." >&2
    exit 1
  fi
fi
./script/ensure-cmake
./script/ensure-curl
./script/ensure-libffi
./script/ensure-libyaml
./script/ensure-mise
mise use "ruby@$DESIRED_RUBY_VERSION"
