#!/usr/bin/env bash

set -e # exit if any command fails

if [[ $OSTYPE != 'darwin'* ]]; then
  echo "Must be running MacOS!" >&2
  exit 1
fi
if ! which -s brew; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo "Close your terminal, reopen, and rerun the prior command." >&2
  exit 1
fi
