#!/usr/bin/env bash

set -e # exit if any command fails

OS="$(uname)"
if [ "$OS" == "Darwin" ]; then
  ./script/ensure-homebrew
  brew install curl
elif [ "$OS" == "Linux" ]; then
  . /etc/os-release
  if [ "$ID" == "ubuntu" ]; then
    sudo apt-get install -y -q curl libcurl4-openssl-dev
  else
    echo "This script supports only ubuntu." >&2
    exit 1
  fi
else
  echo "Unsupported operating system: $OS" >&2
  exit 1
fi
